

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ItemTrackingAPI.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BackLogEntities : DbContext
{
    public BackLogEntities()
        : base("name=BackLogEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<TBL_JIRA_ITEMS> TBL_JIRA_ITEMS { get; set; }

    public virtual DbSet<TBL_RELEASE> TBL_RELEASE { get; set; }

    public virtual DbSet<TBL_TRACK> TBL_TRACK { get; set; }

    public virtual DbSet<TBL_TEAM> TBL_TEAM { get; set; }

    public virtual DbSet<TBK_DEV_STATUS> TBK_DEV_STATUS { get; set; }

    public virtual DbSet<TBL_QA_STATUS> TBL_QA_STATUS { get; set; }

    public virtual DbSet<TBL_QA_DETAILS> TBL_QA_DETAILS { get; set; }

}

}

