//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemTrackingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBK_DEV_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBK_DEV_STATUS()
        {
            this.TBL_JIRA_ITEMS = new HashSet<TBL_JIRA_ITEMS>();
        }
    
        public string StatusCode { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_JIRA_ITEMS> TBL_JIRA_ITEMS { get; set; }
    }
}
