
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ItemTrackingAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_TEAM
{

    public string EmployeeID { get; set; }

    public string EmployeeName { get; set; }

    public int TrackID { get; set; }

    public string IsAdmin { get; set; }

}

}
