
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ItemTrackingAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_QA_STATUS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TBL_QA_STATUS()
    {

        this.TBL_QA_DETAILS = new HashSet<TBL_QA_DETAILS>();

    }


    public string StatusCode { get; set; }

    public string Status { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TBL_QA_DETAILS> TBL_QA_DETAILS { get; set; }

}

}
