//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemTrackingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TEAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_TEAM()
        {
            this.TBL_JIRA_ITEMS = new HashSet<TBL_JIRA_ITEMS>();
            this.TBL_JIRA_ITEMS1 = new HashSet<TBL_JIRA_ITEMS>();
            this.TBL_JIRA_ITEMS2 = new HashSet<TBL_JIRA_ITEMS>();
            this.TBL_JIRA_ITEMS3 = new HashSet<TBL_JIRA_ITEMS>();
            this.TBL_QA_DETAILS = new HashSet<TBL_QA_DETAILS>();
        }
    
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int TrackID { get; set; }
        public string IsAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_JIRA_ITEMS> TBL_JIRA_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_JIRA_ITEMS> TBL_JIRA_ITEMS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_JIRA_ITEMS> TBL_JIRA_ITEMS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_JIRA_ITEMS> TBL_JIRA_ITEMS3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_QA_DETAILS> TBL_QA_DETAILS { get; set; }
    }
}
